import { Plus } from "lucide-react"; import Button from "../../components/ui/Button"; import "./Lotes.css";
const rows=[
["VM-014","Manzana B","180 m²","Carlos Ramírez","$ 65.000.000","$ 46.500.000","$ 18.500.000","Al día"],
["VM-008","Manzana A","165 m²","Diana Torres","$ 58.000.000","$ 48.750.000","$ 9.250.000","Vencido"],
["VM-021","Manzana C","200 m²","Andrés Gómez","$ 72.000.000","$ 48.000.000","$ 24.000.000","Próximo"],
["VM-025","Manzana C","190 m²","Disponible","$ 68.500.000","—","—","Disponible"],
];
const badge=s=>s==="Al día"?"badge-success":s==="Vencido"?"badge-danger":s==="Próximo"?"badge-warning":"badge-neutral";
export default function Lotes({ search }){const t=search.toLowerCase();const filtered=rows.filter(r=>r.join(" ").toLowerCase().includes(t));return <div className="lotes-page page-stack"><header className="page-header"><div><p className="page-eyebrow">Inventario y cartera</p><h1 className="page-title">Lotes</h1><p className="page-description">Control de disponibilidad, compradores y estado financiero de cada lote.</p></div><Button><Plus/> Nuevo lote</Button></header><section className="lotes-metrics"><article className="surface"><small>Total lotes</small><strong>25</strong></article><article className="surface"><small>Disponibles</small><strong>17</strong></article><article className="surface"><small>Vendidos</small><strong>8</strong></article><article className="surface"><small>Área registrada</small><strong>4.620 m²</strong></article></section><section className="lotes-financial"><article className="surface total"><small>Valor total vendido</small><strong>$ 348.500.000</strong></article><article className="surface paid"><small>Total abonado</small><strong>$ 253.750.000</strong></article><article className="surface balance"><small>Saldo pendiente</small><strong>$ 94.750.000</strong></article></section><section className="surface table-shell"><div className="table-scroll"><table className="data-table lotes-table"><thead><tr><th>Lote</th><th>Ubicación</th><th>Área</th><th>Comprador</th><th className="text-right">Valor</th><th className="text-right">Pagado</th><th className="text-right">Saldo</th><th>Estado</th></tr></thead><tbody>{filtered.map(r=><tr key={r[0]}><td><span className="code-pill">{r[0]}</span></td><td>{r[1]}</td><td>{r[2]}</td><td><b>{r[3]}</b></td><td className="text-right money">{r[4]}</td><td className="text-right">{r[5]}</td><td className="text-right money">{r[6]}</td><td><span className={`badge ${badge(r[7])}`}>{r[7]}</span></td></tr>)}</tbody></table></div></section></div>}
